from ventasapp.models.bodega import Bodega
from ventasapp.models.color import Color
from ventasapp.models.genero import Genero
from ventasapp.models.motivo import Motivo
from ventasapp.models.producto import Producto
from ventasapp.models.silueta import Silueta
from ventasapp.models.talla import Talla
from ventasapp.models.venta_no_realizada import VentaNoRealizada
from ventasapp.models.usuario_bodega import Usuario_Bodega
from ventasapp.models.material import Material
from ventasapp.models.diseno import Diseno
