# Generated by Django 4.1.5 on 2023-02-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanorealizada',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.bodega'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.color'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.genero'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventasapp.motivo'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.producto'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='silueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.silueta'),
        ),
        migrations.AlterField(
            model_name='ventanorealizada',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.talla'),
        ),
        migrations.CreateModel(
            name='Usuario_Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.bodega')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
