# Generated by Django 4.1.7 on 2023-06-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0003_diseno_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanorealizada',
            name='diseno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.diseno'),
        ),
        migrations.AddField(
            model_name='ventanorealizada',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventasapp.material'),
        ),
    ]
