# Generated by Django 4.1.7 on 2023-07-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0004_ventanorealizada_diseno_ventanorealizada_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=30)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_llamada', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventasapp.bodega')),
            ],
        ),
    ]
