# Generated by Django 4.1.7 on 2023-07-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0006_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('listar_todos_clientes', 'listar_todos_clientes'), ('importar_clientes', 'importar_clientes')]},
        ),
    ]
